title: "[📢Announcement]:  "
labels: ["announcements"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🚨 Announcement: [Title of Announcement]
        Welcome to the community! This is an important update regarding [Topic of the announcement].
        
  - type: input
    id: announcement_date
    attributes:
      label: Date
      description: The date of your announcement (YYYY-MM-DD).
      placeholder: Enter the date
      value: "2024-01-01"
      
  - type: markdown
    attributes:
      value: |
        ### Details:
        [Provide a detailed description of the update or announcement.]

  - type: textarea
    id: improvements
    attributes:
      label: Top 3 improvements
      description: "What are the top 3 improvements we could make to this project?"
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true

  - type: dropdown
    id: download
    attributes:
      label: Which area of this project could be most improved?
      options:
        - Documentation
        - Pull request review time
        - Bug fix time
        - Release cadence
    validations:
      required: true

  - type: textarea
    id: improvements_2
    attributes:
      label: Top 3 improvements
      description: "What are the top 3 improvements we could make to this project?"
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true

  - type: checkboxes
    id: read-receipt
    attributes:
      label: Acknowledgement (Please check if you've read the announcement)
      options:
        - label: I’ve read and understood this announcement.
    validations:
      required: true
