title: "[Announcement]:  "
labels: ["Announcements"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🚨 Announcement: [Title of Announcement]
        Welcome to the community! This is an important update regarding [Topic of the announcement].
        
  - type: input
    id: announcement_date
    attributes:
      label: Date
      description: The date of your announcement (YYYY-MM-DD).
      placeholder: Enter the date
      
  - type: markdown
    attributes:
      value: |
        ### Details:
        [Provide a detailed description of the update or announcement.]

  - type: checkboxes
    id: read-receipt
    attributes:
      label: Acknowledgement (Please check if you've read the announcement)
      options:
        - label: I’ve read and understood this announcement.
    validations:
      required: true
