title: "[游냍Error: [Describe el problema brevemente]:  "
labels: ["Bug & Errors"]

body:
  - type: markdown
    attributes:
      value: "## Informaci칩n b치sica para entender el error"
      
  - type: input
    id: summary
    attributes:
      label: Resumen del Problema
      description: "Describe brevemente el problema/error que est치s presentando."
      placeholder: "Ejemplo: Error al agregar plugin KunturCheckStyle"
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: "## Detalle del Problema"

  - type: textarea
    id: details
    attributes:
      label: Descripci칩n Detallada
      description: "Proporciona todos los detalles relevantes, como qu칠 estabas haciendo antes de que ocurriera el problema."
      placeholder: |
        Describe el problema, pasos para replicarlo, mensajes de error, etc.
        Por ejemplo:
        1. Agregu칠 el plugin.
        2. Intent칠 realizar la construcci칩n del proyecto.
        3. Apareci칩 un mensaje de error: 'KunturCheckStyle ....'
      render: bash
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Adjuntar Im치genes
        Si tienes capturas de pantalla relacionadas con el problema:
        - Arrastra y suelta las im치genes directamente en este formulario.
        - O pega una imagen desde tu portapapeles (Ctrl+V o Cmd+V).
        - Describe las im치genes en el campo siguiente si es necesario.

  - type: textarea
    id: image_description
    attributes:
      label: Descripci칩n de Im치genes Adjuntas
      description: "Si has adjuntado im치genes, proporciona una breve descripci칩n para cada una."
      placeholder: "Ejemplo: La captura muestra el mensaje de error al tratar de construir el proyecto."
    validations:
      required: false
